language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
matrix:
  include:
    - env: TEST_SUITE=standard
      addons:
        apt:
          packages:
            - texlive-font-utils
            - doxygen
          sources:
            - ubuntu-toolchain-r-test
    - env: TEST_SUITE=standard MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - texlive-font-utils
            - doxygen
    - env: TEST_SUITE=standard MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - texlive-font-utils
            - doxygen
    - env: TEST_SUITE=standard MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - texlive-font-utils
            - doxygen
    - compiler: clang
      env: TEST_SUITE=standard MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - texlive-font-utils
            - doxygen
    - compiler: clang
      env: TEST_SUITE=standard MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - texlive-font-utils
            - doxygen
    # - env: TEST_SUITE=libsemigroups
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       packages:
    #         - doxygen
    #         - gcc-5
    #         - g++-5
before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:dns/gnu -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
install:
    - ci/travis-benchmark-install.sh
    - ci/travis-boost-test-install.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
script:
  - ci/travis-$TEST_SUITE.sh
