language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
matrix:
  include:
    - env: TEST_SUITE=standard
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - libboost-test-dev
    - env: TEST_SUITE=standard MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libboost-test-dev
    - compiler: clang
      env: TEST_SUITE=standard MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - libboost-test-dev
    - env: TEST_SUITE=libsemigroups
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libboost-test-dev
before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:dns/gnu -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
install:
    - ci/travis-benchmark-install.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
script:
  - ci/travis-$TEST_SUITE.sh
